#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
VENV_PY="$ROOT_DIR/.venv_web/bin/python"
APP="services.cycle_web.app:app"
HOST="0.0.0.0"
PORT="8888"

UNIT_NAME="ashare-cycle-web.service"
SYSTEMD_USER_DIR="$HOME/.config/systemd/user"
UNIT_FILE="$SYSTEMD_USER_DIR/$UNIT_NAME"
ENV_DIR="$HOME/.config/ashare_monitor"
ENV_FILE="$ENV_DIR/cycle_web.env"

usage() {
  cat <<USAGE
Usage:
  ./start_service.sh [start|stop|restart|status|logs|install|uninstall]

Notes:
  - 服务固定监听 8888（HOST=$HOST, PORT=$PORT）
  - 使用 systemd user service 托管
USAGE
}

load_env_from_zshrc() {
  if [ ! -f "$HOME/.zshrc" ]; then
    return
  fi

  # Prefer loading env by sourcing ~/.zshrc in a subshell (portable mode).
  env_snapshot=$( (set +u; . "$HOME/.zshrc" >/dev/null 2>&1; env) 2>/dev/null || true )

  for key in \
    CYCLE_WEB_MYSQL_HOST \
    CYCLE_WEB_MYSQL_PORT \
    CYCLE_WEB_MYSQL_USER \
    CYCLE_WEB_MYSQL_DATABASE \
    CYCLE_WEB_MYSQL_PASSWORD \
    MYSQL_HOST \
    MYSQL_PORT \
    MYSQL_USER \
    MYSQL_DATABASE \
    MYSQL_PASSWORD
  do
    eval "cur=\${$key:-}"
    if [ -n "$cur" ]; then
      continue
    fi

    val=$(printf '%s\n' "$env_snapshot" | awk -F= -v k="$key" '$1==k { sub($1"=",""); print; exit }')
    if [ -z "$val" ]; then
      line=$(grep -E "^export[[:space:]]+$key=" "$HOME/.zshrc" | tail -n 1 || true)
      val=${line#*=}
      case "$val" in
        \"*\")
          val=${val#\"}
          val=${val%\"}
          ;;
        \'*\')
          val=${val#\'}
          val=${val%\'}
          ;;
      esac
    fi
    if [ -n "$val" ]; then
      export "$key=$val"
    fi
  done
}

require_systemd_user() {
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "[error] systemctl not found"
    exit 1
  fi
  if ! systemctl --user show-environment >/dev/null 2>&1; then
    echo "[error] systemd user manager unavailable"
    exit 1
  fi
}

ensure_dirs() {
  mkdir -p "$ROOT_DIR/logs" "$SYSTEMD_USER_DIR" "$ENV_DIR"
}

write_env_file() {
  python3 - "$ENV_FILE" <<'PY'
import os
import shlex
import sys
from pathlib import Path

path = Path(sys.argv[1])
path.parent.mkdir(parents=True, exist_ok=True)

def pick(*keys, default=""):
    for k in keys:
        v = os.getenv(k)
        if v is not None and str(v).strip() != "":
            return str(v).strip()
    return default

host = pick("CYCLE_WEB_MYSQL_HOST", "MYSQL_HOST", default="192.168.1.15")
port = pick("CYCLE_WEB_MYSQL_PORT", "MYSQL_PORT", default="3306")
user = pick("CYCLE_WEB_MYSQL_USER", "MYSQL_USER", default="myuser")
database = pick("CYCLE_WEB_MYSQL_DATABASE", "MYSQL_DATABASE", default="mydb")
password = pick("CYCLE_WEB_MYSQL_PASSWORD", "MYSQL_PASSWORD", default="")

values = {
    "CYCLE_WEB_MYSQL_HOST": host,
    "CYCLE_WEB_MYSQL_PORT": port,
    "CYCLE_WEB_MYSQL_USER": user,
    "CYCLE_WEB_MYSQL_DATABASE": database,
    "CYCLE_WEB_MYSQL_PASSWORD": password,
    "MYSQL_HOST": host,
    "MYSQL_PORT": port,
    "MYSQL_USER": user,
    "MYSQL_DATABASE": database,
    "MYSQL_PASSWORD": password,
}

with path.open("w", encoding="utf-8") as f:
    f.write("# Generated by start_service.sh\n")
    for key, value in values.items():
        f.write(f"{key}={shlex.quote(value)}\n")
PY

  if [ -z "${CYCLE_WEB_MYSQL_PASSWORD:-${MYSQL_PASSWORD:-}}" ]; then
    echo "[warn] MySQL password not found in shell env; service may fail DB calls."
    echo "       please export CYCLE_WEB_MYSQL_PASSWORD or MYSQL_PASSWORD, then rerun."
  fi
}

write_unit_file() {
  cat >"$UNIT_FILE" <<EOF
[Unit]
Description=A-Share Cycle Web Service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$ROOT_DIR
Environment=PYTHONUNBUFFERED=1
EnvironmentFile=-$ENV_FILE
ExecStart=$VENV_PY -m uvicorn $APP --host $HOST --port $PORT
Restart=always
RestartSec=2
KillSignal=SIGTERM
TimeoutStopSec=20

[Install]
WantedBy=default.target
EOF
}

install_unit() {
  ensure_dirs
  require_systemd_user
  load_env_from_zshrc

  if [ ! -x "$VENV_PY" ]; then
    echo "[error] Python not found: $VENV_PY"
    exit 1
  fi

  write_env_file
  write_unit_file
  systemctl --user daemon-reload
  systemctl --user enable "$UNIT_NAME" >/dev/null
  echo "[ok] installed $UNIT_NAME"
}

start() {
  install_unit
  systemctl --user start "$UNIT_NAME"
  sleep 1
  status
}

stop() {
  require_systemd_user
  systemctl --user stop "$UNIT_NAME" >/dev/null 2>&1 || true
  echo "[ok] service stopped"
}

restart() {
  install_unit
  systemctl --user restart "$UNIT_NAME"
  sleep 1
  status
}

status() {
  require_systemd_user
  if systemctl --user is-active --quiet "$UNIT_NAME"; then
    echo "[ok] running ($UNIT_NAME)"
  else
    echo "[ok] not running ($UNIT_NAME)"
  fi
  echo "[info] bind=$HOST:$PORT"
  echo "[info] ui=http://127.0.0.1:$PORT/ui/"
  echo "[info] health=http://127.0.0.1:$PORT/api/health"
}

show_logs() {
  require_systemd_user
  journalctl --user -u "$UNIT_NAME" -n 120 --no-pager
}

uninstall() {
  require_systemd_user
  systemctl --user stop "$UNIT_NAME" >/dev/null 2>&1 || true
  systemctl --user disable "$UNIT_NAME" >/dev/null 2>&1 || true
  rm -f "$UNIT_FILE"
  systemctl --user daemon-reload
  echo "[ok] uninstalled $UNIT_NAME"
}

cmd="${1:-start}"
case "$cmd" in
  start) start ;;
  stop) stop ;;
  restart) restart ;;
  status) status ;;
  logs) show_logs ;;
  install) install_unit ;;
  uninstall) uninstall ;;
  -h|--help|help) usage ;;
  *)
    echo "[error] unknown command: $cmd"
    usage
    exit 1
    ;;
esac
